pipeline {
  agent any
    
  environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
    }
  stages {
    stage('Checkout') {
      steps {
        git branch: 'main',
          credentialsId: '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',
          url: 'https://github.com/DamithGit92/Python-Project.git'
      }
    }
    stage('Build') {
      steps {
        sh 'docker build -t damithv1/cicd-e2e:${BUILD_NUMBER} .'
      }
    }
    stage('Deploy') {
      steps {
        sh 'docker push damithv1/cicd-e2e:${BUILD_NUMBER}'
      }
    }
  }
}
